import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/ Navbar";
import HomeBanner from "./components/HomeBanner";
import SubNavbar from "./components/SubNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Twin AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
